# Generated by Django 4.1.3 on 2022-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_comment_author_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
