# Generated by Django 4.1.3 on 2022-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='userid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
