# Generated by Django 4.1.3 on 2022-11-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_account_created_at_alter_account_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
    ]
