# Generated by Django 4.1.3 on 2022-11-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_postlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostList',
        ),
    ]
