# Generated by Django 4.1.3 on 2022-12-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_post_author_alter_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
