# Generated by Django 4.1.3 on 2022-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_remove_user_user_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
