# Generated by Django 4.1.3 on 2022-12-04 14:11

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_comment_nickname_post_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default=user.models.Account.get_nickname, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default=user.models.Account.get_nickname, max_length=50, null=True),
        ),
    ]
