# Generated by Django 4.1.3 on 2022-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_comment_nickname_alter_post_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
