# Generated by Django 4.0.4 on 2022-11-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='유저 이메일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='유저 이름'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=200, unique=True, verbose_name='유저 닉네임'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=500, verbose_name='유저 비밀번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNum',
            field=models.CharField(max_length=200, unique=True, verbose_name='유저 핸드폰 번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='계정 업데이트 시간'),
        ),
    ]
