# Generated by Django 4.0.4 on 2022-12-02 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_options_alter_account_table'),
        ('adv', '0004_remove_comment_modified_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.account'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
